# Generated by Django 3.0.8 on 2020-08-17 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='created_by',
            field=models.CharField(default='Coder', max_length=200),
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='user_members',
            field=models.ManyToManyField(to='club.UserMembers'),
        ),
        migrations.AddField(
            model_name='club',
            name='user_staffs',
            field=models.ManyToManyField(to='club.UserStaffs'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(upload_to='media/images/club_pic/logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermembers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userstaffs',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
