# Generated by Django 3.0.7 on 2020-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(upload_to='media/images/club_pic/logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermembers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userstaffs',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
