# Generated by Django 3.0.8 on 2020-09-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
    ]
