# Generated by Django 3.0.8 on 2020-08-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_description', models.TextField(max_length=1000)),
                ('news_date', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('all', models.BooleanField(default=False)),
                ('club_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.UserStaffs')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/club_pic/gallery')),
                ('club_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField(max_length=1000)),
                ('event_date', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('all', models.BooleanField(default=False)),
                ('club_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.UserStaffs')),
                ('interested_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.UserMembers')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('interested_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.UserMembers')),
            ],
        ),
    ]
