# Generated by Django 3.0.7 on 2020-08-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_assignmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ManyToManyField(to='club.Club'),
        ),
        migrations.DeleteModel(
            name='AssignMember',
        ),
    ]
