# Generated by Django 3.0.7 on 2020-09-02 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpresident',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
