# Generated by Django 3.0.7 on 2020-08-16 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200816_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='user_member',
            field=models.ManyToManyField(to='club.UserMembers'),
        ),
        migrations.AddField(
            model_name='club',
            name='user_staff',
            field=models.ManyToManyField(to='club.UserStaffs'),
        ),
    ]
