# Generated by Django 2.1.5 on 2020-08-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_application_event_gallery_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpresident',
            name='club_name',
        ),
        migrations.RemoveField(
            model_name='contactpresident',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='members',
        ),
        migrations.AddField(
            model_name='application',
            name='members',
            field=models.ManyToManyField(to='club.UserMembers'),
        ),
        migrations.RemoveField(
            model_name='club',
            name='user',
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.ForeignKey(default='Absek', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='club',
            name='user_staffs',
        ),
        migrations.AddField(
            model_name='club',
            name='user_staffs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.UserStaffs'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='interested_members',
        ),
        migrations.AddField(
            model_name='event',
            name='interested_members',
            field=models.ManyToManyField(to='club.UserMembers'),
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='club_img',
        ),
        migrations.AddField(
            model_name='gallery',
            name='club_img',
            field=models.ManyToManyField(to='club.Club'),
        ),
    ]
