# Generated by Django 3.0.7 on 2020-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200828_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='club_img',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/club_pic/gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/club_pic/gallery'),
        ),
    ]
