# Generated by Django 3.0.7 on 2020-08-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_user_pp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstaffdetail',
            name='user_staff',
        ),
        migrations.DeleteModel(
            name='UserMemberDetail',
        ),
        migrations.DeleteModel(
            name='UserStaffDetail',
        ),
    ]
