# Generated by Django 3.0.7 on 2020-09-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200902_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpresident',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.UserMembers'),
        ),
    ]
