# Generated by Django 3.0.8 on 2020-08-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200816_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='user_member',
            new_name='user_members',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='user_staff',
            new_name='user_staffs',
        ),
    ]
