# Generated by Django 2.1.5 on 2020-08-18 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200818_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='user_staffs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.UserStaffs'),
        ),
        migrations.AlterField(
            model_name='contactpresident',
            name='club',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contactpresident',
            name='member',
            field=models.CharField(max_length=300),
        ),
    ]
