# Generated by Django 3.0.7 on 2020-08-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200901_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club',
            field=models.ManyToManyField(blank=True, null=True, to='club.Club'),
        ),
    ]
