# Generated by Django 3.0.7 on 2020-08-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200829_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pp',
            new_name='profile_pic',
        ),
    ]
