# Generated by Django 2.1.5 on 2020-08-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200817_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPresident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('member_name', models.CharField(max_length=200)),
                ('message_title', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
