# Generated by Django 3.0.7 on 2020-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200902_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpresident',
            name='club',
            field=models.CharField(max_length=200),
        ),
    ]
