# Generated by Django 3.0.7 on 2020-09-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200901_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='club',
        ),
    ]
