# Generated by Django 3.0.7 on 2020-09-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20200902_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpresident',
            name='username',
        ),
    ]
