# Generated by Django 3.0.7 on 2020-08-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_memberapplicationrecord_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
