# Generated by Django 3.0.7 on 2020-09-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_remove_contactpresident_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='images/club_pic/logo/art.png', upload_to='images/club_pic/logo'),
        ),
    ]
