# Generated by Django 3.0.7 on 2020-08-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_delete_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpresident',
            old_name='member',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='contactpresident',
            name='club_name',
        ),
        migrations.RemoveField(
            model_name='contactpresident',
            name='member_name',
        ),
        migrations.AlterField(
            model_name='contactpresident',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club'),
        ),
        migrations.AlterField(
            model_name='usermembers',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club'),
        ),
    ]
