# Generated by Django 3.0.7 on 2020-08-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20200829_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
